### ISSUE TITLE
using `postWager` in interact interface gives compilation error

### ISSUE THREAD

**Issue by sin3point14** [reach-sh/reach-lang#183]
```js
const FunderInterface =
{
    ...CommonInterface,
    getBounty: Fun([], Object({
        deadline: UInt,
        amt: UInt,
    })),
    postWager: Fun([], Null)
}
```
gives
```
file:///app/build/index.main.mjs:382
  stdlib.protect(ctc2, await interact.postWager(), {
                                      ^

TypeError: interact.postWager is not a function
    at Module.Funder (file:///app/build/index.main.mjs:382:39)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
    at async file:///app/index.mjs:122:5
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @reach-sh/stonk-wars-index@ index: `node --experimental-modules --unhandled-rejections=strict index.mjs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @reach-sh/stonk-wars-index@ index script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-11T02_59_57_847Z-debug.log
ERROR: 1
Makefile.index:20: recipe for target 'run-target' failed
make[1]: *** [run-target] Error 1
make[1]: Leaving directory '/mnt/d/my-projs/stonk-wars'
Makefile.index:16: recipe for target 'run' failed
make: *** [run] Error 2
```

**Comment by sin3point14** [comment]
my bad, mistook something else for an error!
