### ISSUE TITLE
I believe parallelReduce fails on Ethereum.

### ISSUE THREAD

**Issue by hagenhaus** [reach-sh/reach-lang#193]
[See this video](https://www.youtube.com/watch?v=AVXRFtl0pU4) to watch a parallelReduce test that passes on Algorand and fails on Ethereum. Video includes tests specs, link to github repo, and error msg at the end. I'll show the error msg here, too:

```
/stdlib/node_modules/@ethersproject/logger/lib/index.js:187
        var error = new Error(message);
                    ^

Error: missing response (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":94,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"code":"ECONNRESET"}, url="http://ethereum-devnet:8545", code=SERVER_ERROR, version=web/5.3.0)
    at Logger.makeError (/stdlib/node_modules/@ethersproject/logger/lib/index.js:187:21)
    at Logger.throwError (/stdlib/node_modules/@ethersproject/logger/lib/index.js:196:20)
    at /stdlib/node_modules/@ethersproject/web/lib/index.js:213:36
    at step (/stdlib/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.throw (/stdlib/node_modules/@ethersproject/web/lib/index.js:14:53)
    at rejected (/stdlib/node_modules/@ethersproject/web/lib/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: 'missing response',
  code: 'SERVER_ERROR',
  requestBody: '{"method":"eth_blockNumber","params":[],"id":94,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  serverError: Error: socket hang up
      at connResetException (internal/errors.js:607:14)
      at Socket.socketOnEnd (_http_client.js:499:23)
      at Socket.emit (events.js:388:22)
      at endReadableNT (internal/streams/readable.js:1336:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21) {
    code: 'ECONNRESET'
  },
  url: 'http://ethereum-devnet:8545'
```

**Comment by jeapostrophe** [comment]
I made an automated version of this program --- https://github.com/hagenhaus/reach-examples/pull/1

It does not error.

Do you always get this error? Can you monitor Docker at the same time and see if your eth devnet crashes? The error means "I tried to contact the Ethereum devnet node but failed"

**Comment by hagenhaus** [comment]
Okay. How do I monitor Docker?

**Comment by jeapostrophe** [comment]
No prob. As for how to monitor Docker, when you run Docker Desktop, it will show you a list of running containers, you can click on one and see its current output, that might have been helpful. There's a command-line way to do that too. If when your machine was hot, if you did `reach docker-reset`, I bet it would have killed a bunch of old containers and things would have cleared up too. We (Reach) are not yet doing a good job killing old stuff you don't need anymore. I have a task for Matt to fix that.
