### ISSUE TITLE
Error: Unrecognized REACH_CONNECTOR_MODE='ALGO-devnet' on reach run

### ISSUE THREAD

**Issue by mrweiner** [reach-sh/reach-lang#226]
After `./reach ugrade && ./reach update`, running `REACH_CONNECTOR_MODE=ALGO ./reach run` is throwing an error. There are two issue here:

1. Error: Unrecognized REACH_CONNECTOR_MODE='ALGO-devnet'
2. There's a WARNING for orphaned containers, but `--remove-orphans` is not a valid flag for `reach run`

```
REACH_CONNECTOR_MODE=ALGO ./reach run 
/home/weiner/Documents/reach/handcrafted-reach/reach compile index.rsh
Verifying knowledge assertions
Verifying for generic connector
  Verifying when ALL participants are honest
  Verifying when NO participants are honest
  Verifying when ONLY "HandcraftedFeeAcct" is honest
  Verifying when ONLY "HandcraftedTaxAcct" is honest
  Verifying when ONLY "Merchant" is honest
  Verifying when ONLY "PotentialBuyer" is honest
Checked 484 theorems; No failures!
docker build -f Dockerfile.index --tag=reachsh/reach-app-handcrafted-reach-index:latest .
Sending build context to Docker daemon  1.509MB
Step 1/4 : FROM reachsh/runner:0.1
 ---> 4df0a0fa6537
Step 2/4 : COPY . /app
 ---> 51b2843b37a0
Step 3/4 : RUN cp /app/package.json.index /app/package.json
 ---> Running in 0ee73eda6d9a
Removing intermediate container 0ee73eda6d9a
 ---> bc9a26128a26
Step 4/4 : CMD ["index"]
 ---> Running in 7188f4b73b52
Removing intermediate container 7188f4b73b52
 ---> 0bffd9e9670c
Successfully built 0bffd9e9670c
Successfully tagged reachsh/reach-app-handcrafted-reach-index:latest
/home/weiner/Documents/reach/handcrafted-reach/reach run index
make[1]: Entering directory '/home/weiner/Documents/reach/handcrafted-reach'
docker build -f Dockerfile.index --tag=reachsh/reach-app-handcrafted-reach-index:latest .
Sending build context to Docker daemon  1.509MB
Step 1/4 : FROM reachsh/runner:0.1
 ---> 4df0a0fa6537
Step 2/4 : COPY . /app
 ---> Using cache
 ---> 51b2843b37a0
Step 3/4 : RUN cp /app/package.json.index /app/package.json
 ---> Using cache
 ---> bc9a26128a26
Step 4/4 : CMD ["index"]
 ---> Using cache
 ---> 0bffd9e9670c
Successfully built 0bffd9e9670c
Successfully tagged reachsh/reach-app-handcrafted-reach-index:latest
docker-compose -f "docker-compose.yml.index" run --rm reach-app-handcrafted-reach-index-${REACH_CONNECTOR_MODE} index
WARNING: Found orphan containers (handcrafted-reach_algorand-postgres-db_1, handcrafted-reach_ethereum-devnet_1, handcrafted-reach_algorand-devnet_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting handcrafted-reach_devnet-algo-pg_1 ... done
Starting handcrafted-reach_devnet-algo_1    ... done

> @reach-sh/handcrafted-reach-index@ index /app
> node --experimental-modules --unhandled-rejections=strict index.mjs

/stdlib/dist/cjs/ConnectorMode.js:41
        throw Error("Unrecognized REACH_CONNECTOR_MODE='" + connectorMode + "'");
              ^

Error: Unrecognized REACH_CONNECTOR_MODE='ALGO-devnet'
    at Object.canonicalizeConnectorMode (/stdlib/dist/cjs/ConnectorMode.js:41:15)
    at loadStdlib (/stdlib/dist/cjs/loader.js:55:41)
    at loadStdlib (/stdlib/dist/cjs/loader.js:39:16)
    at file:///app/index.mjs:5:24
    at file:///app/index.mjs:222:3
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @reach-sh/handcrafted-reach-index@ index: `node --experimental-modules --unhandled-rejections=strict index.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @reach-sh/handcrafted-reach-index@ index script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-22T00_38_24_122Z-debug.log
make[1]: *** [Makefile.index:20: run-target] Error 1
make[1]: Leaving directory '/home/weiner/Documents/reach/handcrafted-reach'
```

**Comment by DanBurton** [comment]
@mrweiner: Sorry, I think this is an issue where `reach upgrade` gave an updated `reach` script when the corresponding images weren't uploaded yet. They are now (images & js updated to c0117e03), so please `reach update` and try again.

**Comment by DanBurton** [comment]
You can try `reach docker-reset` to clean up the docker orphans. (The `--remove-orphans` flag refers to the `docker-compose` command that `reach` invokes on your behalf.)

**Comment by mrweiner** [comment]
Thanks @DanBurton -- `reach update && reach clean` did the trick. Seems to be working as expected now. And thanks for the clarification `reach docker-reset`. Realized that was coming from docker after I posted.

**Comment by mattaudesse** [comment]
Hey @mrweiner, I'm going to go ahead and close this issue since it looks like you're all set now, but if that's not the case we can reopen.
