### ISSUE TITLE
tut-6 gives compiler error

### ISSUE THREAD

**Issue by Zetsuboii** [reach-sh/reach-lang#240]
Running the tutorial 6 gives following output

```
Creating tut_reach-app-tut-index-ETH-devnet_run ... done

> @reach-sh/tut-index@ index /app
> node --experimental-modules --unhandled-rejections=strict index.mjs

Alice played Rock
  Bob takes his sweet time...
  Bob takes his sweet time...
  Bob takes his sweet time...
  Bob takes his sweet time...
  Bob takes his sweet time...
  Bob takes his sweet time...
  Bob takes his sweet time...
  Bob takes his sweet time...
  Bob takes his sweet time...
  Bob takes his sweet time...
Bob played Rock
impossible: The message you are trying to send appears to be invalid.
Error: execution reverted
    at getResult (/stdlib/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:128:21)
    at processJsonFunc (/stdlib/node_modules/@ethersproject/web/lib/index.js:309:22)
    at /stdlib/node_modules/@ethersproject/web/lib/index.js:241:46
    at step (/stdlib/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.next (/stdlib/node_modules/@ethersproject/web/lib/index.js:14:53)
    at fulfilled (/stdlib/node_modules/@ethersproject/web/lib/index.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 3,
  data: '0x100960cb000000000000000000000000000000000000000000000000000000000000000b'
}
args:
[
  [
    '0x9fd7B8775CAD440CEd4aD4aE0B071F2e875b476c',
    BigNumber { _hex: '0x4563918244f40000', _isBigNumber: true },
    BigNumber {
      _hex: '0xa9293aca120ca35e2ee05103aa7494aa3ac35c263c307dcb5d1c281dd6898cf2',
      _isBigNumber: true
    },
    BigNumber { _hex: '0x0a', _isBigNumber: true },
    BigNumber { _hex: '0x8e', _isBigNumber: true }
  ],
  [ BigNumber { _hex: '0x00', _isBigNumber: true } ]
]
/stdlib/dist/cjs/ETH_like.js:790
                                            throw Error(dhead + " REPEAT @ " + block_send_attempt + " x " + block_repeat_count);
                                                  ^

Error: C1C1,C1C1,send,m2,time,142,SEND REPEAT @ 142 x 33
    at Object.<anonymous> (/stdlib/dist/cjs/ETH_like.js:790:51)
    at step (/stdlib/dist/cjs/ETH_like.js:44:23)
    at Object.next (/stdlib/dist/cjs/ETH_like.js:25:53)
    at fulfilled (/stdlib/dist/cjs/ETH_like.js:16:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @reach-sh/tut-index@ index: `node --experimental-modules --unhandled-rejections=strict index.mjs`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @reach-sh/tut-index@ index script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-06T09_00_40_061Z-debug.log
ERROR: 1
make[1]: *** [run-target] Error 1
make: *** [run] Error 2
```

**Comment by cswenor** [comment]
This happens only when Bob times out.

**Comment by cswenor** [comment]
On Algorand it doesn't give an error but it just freezes after Bob tries to play his hand after he times out.

**Comment by jeapostrophe** [comment]
Thanks. I believe I fixed this and it will be released shortly.
