### ISSUE TITLE
Adding Events to contract cause frontend to error

### ISSUE THREAD

**Issue by AwolDes** [reach-sh/reach-lang#464]
**Describe the error**

After adding in new [`Events`](https://docs.reach.sh/rsh/appinit/#rsh_Events), my contract compiles successfully but errors on the frontend with the following before a `pay` call, and before entering a `parallelReduce`. It seems to happen after a `publish`.

```
Error: 2SOW failed to call m1: [object Object]
    at contracts/node_modules/@reach-sh/stdlib/dist/cjs/ALGO.js:1810:59
    at step (contracts/node_modules/@reach-sh/stdlib/dist/cjs/ALGO.js:54:23)
    at Object.throw (contracts/node_modules/@reach-sh/stdlib/dist/cjs/ALGO.js:35:53)
    at step (contracts/node_modules/@reach-sh/stdlib/dist/cjs/ALGO.js:39:139)
    at Object.throw (contracts/node_modules/@reach-sh/stdlib/dist/cjs/ALGO.js:35:53)
    at rejected (contracts/node_modules/@reach-sh/stdlib/dist/cjs/ALGO.js:27:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**To Reproduce**

Event:
```javascript
const Announcer = Events('Announcer', {
  created: [Address, Object(user)],
  deleted: [Address, Object(user)]
});
// called like this within a API in a parallelReduce
Announcer.created(this, user);
```
I can share more information privately if it would help.

**Expected behavior**

I expect the program would not error with events added.

**Extra information**
This is running on the Algorand network
```
./reach hashes
reach: 7b246c0c
reach-cli: 7b246c0c
react-runner: 7b246c0c
rpc-server: 7b246c0c
runner: 7b246c0c
devnet-algo: 7b246c0c
devnet-cfx: 7b246c0c
devnet-eth: 7b246c0c
```

**Comment by AwolDes** [comment]
Resolved by updating `stdlib` version & updating to latest Reach release.
